<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet ekr_test?>
<leo_file>
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals/>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="gcross.20110410073838.1274" a="E"><vh>@path viewpoint</vh>
<v t="gcross.20110410073838.1275"><vh>@file Tree.java</vh></v>
</v>
</vnodes>
<tnodes>
<t tx="gcross.20110410073838.1274"></t>
</tnodes>
</leo_file>
